CREATE DATABASE CARS_DATASET ;

-- Top 5 Manufacturers with the Most Cars:
SELECT * FROM cars;
SELECT MAKE , COUNT(*) AS NUM_OF_CARS 
FROM CARS 
GROUP BY  MAKE 
ORDER BY 2 desc 
LIMIT 5;

-- Average Initial Price by Car Type:
SELECT CAR_TYPE , AVG(INITIAL_PRICE) AS AVG_PRICE
FROM CARS 
GROUP BY CAR_TYPE 
ORDER BY 2 DESC ;

-- Safety Classification Distribution:
SELECT SAFTEY_CLASSIFICATION ,COUNT(*) AS CLASSIFICATION_COUNT
FROM CARS 
GROUP BY SAFTEY_CLASSIFICATION ;

-- Average Mileage for Each Seating Capacity:
SELECT SEATING_CAPACITY , AVG(MILEAGE) AS AVG_MILAGE
FROM CARS 
GROUP BY SEATING_CAPACITY ,ENGINE_TYPE;

-- Fuel Efficiency Comparison by Engine Type:
SELECT ENGINE_TYPE, AVG(MILEAGE) AS AVG_MILAGE
FROM CARS
GROUP BY ENGINE_TYPE 
ORDER BY 2 DESC ; 

-- Safety Index Distribution by Car Type:
SELECT CAR_TYPE,MIN(SAFTEY_INDEX) AS MIN_SAFETY,MAX(SAFTEY_INDEX) AS MAX_SAFETY 
FROM CARS
GROUP BY CAR_TYPE ;

-- AVERAGE SAFETY INDEX FOR EACH MANUFACTURER
SELECT MAKE , AVG(SAFTEY_INDEX) AS AVG_SAFETY
FROM cars
GROUP BY MAKE 
ORDER BY 2 DESC ;

-- Fuel Efficiency Comparison for Top Manufacturers:
SELECT MAKE , AVG(MILEAGE) AS AVG_MILEAGE
FROM CARS 
GROUP BY MAKE 
ORDER BY 2 DESC ;

-- Average Initial Price by Seating Capacity and Car Type:
SELECT SEATING_CAPACITY, CAR_TYPE,AVG(INITIAL_PRICE) AS AVG_INITIAL_PRICE
FROM CARS 
GROUP BY SEATING_CAPACITY ,CAR_TYPE
ORDER BY 3 DESC ;

-- Ranking Cars by Safety Index within Each Car Type:
SELECT*FROM CARS ;
SELECT Name, Car_Type, SaftEy_Index,
       DENSE_RANK() OVER (PARTITION BY Car_Type ORDER BY SaftEy_Index DESC) AS Safety_Rank
FROM CARS ;

-- Top 5 Color Variants for Each Manufacturer:
SELECT MAKE , COLOUR, COUNT(*) AS COLOUR_COUNT
FROM CARS 
GROUP BY MAKE,COLOUR 
ORDER BY 3 DESC
LIMIT 5; 

-- Total number of cars across each variant
SELECT MAKE ,SUM(CASE WHEN ENGINE_TYPE='PETROL' THEN 1 ELSE 0 END ) AS PETROL_CAR ,
	   SUM(CASE WHEN ENGINE_TYPE='DIESEL' THEN 1 ELSE 0 END ) AS DIESEL_CAR 
FROM CARS 
GROUP BY MAKE ;
percentage_pf_people_vacionatedSELECT* FROM CARS ;



